QuoteApp/Models/ErrorViewModel.cs
namespace QuoteApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

QuoteApp/Models/Quote.cs
namespace QuoteApp.Models
{
    public class Quote
    {
        public int Id { get; set; }
        public required string Quotation { get; set; }
        public required string Author { get; set; }
        public required string Genre { get; set; }

        public string? UserId { get; set; }

        public Quote()
        {

        }
    }
}

QuoteApp/Controllers/QuotesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using QuoteApp.Data;
using QuoteApp.Models;
using System.Security.Claims;

namespace QuoteApp.Controllers
{
    public class QuotesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public QuotesController(ApplicationDbContext context)
        {
            _context = context;
        }

        /*public async Task<IActionResult> Index()
        {
            return View(await _context.Quote.ToListAsync());
        }*/


        // GET: ShowSearchForm
        public IActionResult ShowSearchForm()
        {
            return View();
        }

        // GET: Quotes
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewBag.SortParam = sortOrder;
            if (searchString == ViewBag.SortParam)
            {
                searchString += "_desc";
                ViewBag.SortParam = "";
            }
            else
            {
                ViewBag.SortParam = searchString;
            }
            var quotes = from s in _context.Quote
                           select s;
            switch (searchString)
            {
                case "quotation":
                    quotes = quotes.OrderBy(s => s.Quotation);
                    break;
                case "quotation_desc":
                    quotes = quotes.OrderByDescending(s => s.Quotation);
                    break;
                case "author":
                    quotes = quotes.OrderBy(s => s.Author);
                    break;
                case "author_desc":
                    quotes = quotes.OrderByDescending(s => s.Author);
                    break;
                case "genre":
                    quotes = quotes.OrderBy(s => s.Genre);
                    break;
                case "genre_desc":
                    quotes = quotes.OrderByDescending(s => s.Genre);
                    break;
                default:
                    break;
            }
            return View(quotes.ToList());
        }

        public async Task<IActionResult> ShowSearchResults(string SearchTermQuotation, string SearchTermAuthor, string SearchTermGenre)
        {
            return View("Index", await _context.Quote
                .Where(q => q.Quotation.Contains(SearchTermQuotation) || string.IsNullOrEmpty(SearchTermQuotation))
                .Where(q => q.Author.Contains(SearchTermAuthor) || string.IsNullOrEmpty(SearchTermAuthor))
                .Where(q => q.Genre.Contains(SearchTermGenre) || string.IsNullOrEmpty(SearchTermGenre))
                .ToListAsync());
        }

        // GET: Quotes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quote = await _context.Quote
                .FirstOrDefaultAsync(m => m.Id == id);
            if (quote == null)
            {
                return NotFound();
            }

            return View(quote);
        }

        // GET: Quotes/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Quotes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(Quote quote)
        {
            if (ModelState.IsValid)
            {
                // Dodajemy identyfikator użytkownika do cytatu
                quote.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                _context.Add(quote);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(quote);
        }

        // GET: Quotes/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quote = await _context.Quote.FindAsync(id);
            if (quote == null || quote.UserId != User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                return NotFound();
            }
            return View(quote);
        }

        // POST: Quotes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, Quote quote)
        {
            if (id != quote.Id || quote.UserId != User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(quote);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuoteExists(quote.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(quote);
        }

        // GET: Quotes/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quote = await _context.Quote
                .FirstOrDefaultAsync(m => m.Id == id);
            if (quote == null || quote.UserId != User.FindFirstValue(ClaimTypes.NameIdentifier) || string.IsNullOrEmpty(quote.UserId))
            {
                return NotFound();
            }

            return View(quote);
        }

        // POST: Quotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var quote = await _context.Quote.FindAsync(id);
            if (quote != null && quote.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                _context.Quote.Remove(quote);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool QuoteExists(int id)
        {
            return _context.Quote.Any(e => e.Id == id);
        }
    }
}

// EOF

QuoteApp/Views/Quotes/Create.cshtml
@model QuoteApp.Models.Quote

@{
    ViewData["Title"] = "Create a new Quote";
}



<h4>Add a Quote</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Quotation" class="control-label"></label>
                <input asp-for="Quotation" class="form-control" />
                <span asp-validation-for="Quotation" class="text-danger"></span>
            </div><br>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div><br>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div><br>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <input type="submit" asp-action="Index" value="Back to List" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

QuoteApp/Views/Quotes/Delete.cshtml
@model QuoteApp.Models.Quote

@{
    ViewData["Title"] = "Delete";
}



<h4>Are you sure you want to delete this?</h4>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quotation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quotation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />   <input asp-action="Index" value="Back to List" type="submit" class="btn btn-primary">
    </form>
</div>

QuoteApp/Views/Quotes/Details.cshtml
@using System.Security.Claims
@model QuoteApp.Models.Quote

@{
    ViewData["Title"] = "Quote Details";
}


<div>
    <h4>Quote details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quotation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quotation)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
    </dl>
</div>
<div>
    @if (@Model?.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier))
    {
        <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
    }
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

QuoteApp/Views/Quotes/Edit.cshtml
@model QuoteApp.Models.Quote

@{
    ViewData["Title"] = "Edit Quote";
}

<h4>Edit a Quote</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Quotation" class="control-label"></label>
                <input asp-for="Quotation" class="form-control" />
                <span asp-validation-for="Quotation" class="text-danger"></span>
            </div><br>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div><br>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div><br>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <input type="submit" asp-action="Index" value="Back to List" class="btn btn-primary" />
            </div>
            <input type="hidden" asp-for="UserId" />
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

QuoteApp/Views/Quotes/Index.cshtml
@using System.Security.Claims
@model IEnumerable<QuoteApp.Models.Quote>

@{
    ViewData["Title"] = "Available Quote";
}

<h4>Here is a list of available Quotes</h4>


<table class="table">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                @Html.ActionLink("Quotation", "Index", new { sortOrder = ViewBag.SortParam, searchString = "quotation" })
            </th>
            <th>
                @Html.ActionLink("Author", "Index", new { sortOrder = ViewBag.SortParam, searchString = "author" })
            </th>
            <th>
                @Html.ActionLink("Genre", "Index", new { sortOrder = ViewBag.SortParam, searchString = "genre" })
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>


        @{
            int counter = 1;
        }

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @counter
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quotation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @if (item.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier) || string.IsNullOrEmpty(item.UserId))
                    {
                        <text>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                        </text>
                    }
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                </td>
            </tr>
            counter++;
        }
    </tbody>
</table>

<br>
<form asp-action="Create">
    <input type="submit" value="Create New" class="btn btn-primary" />
</form>


QuoteApp/Views/Quotes/ShowSearchForm.cshtml
@{
    ViewData["Title"] = "Search your favorite Quote";
}

<h4>Search for a Quote</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <h4>Search by quotation</h4>
            <div class="form-group" name="Search quotation">
                <label for="SearchTermQuotation" class="control-label"></label>
                <input name="SearchTermQuotation" class="form-control" />
            </div>
            <br>
            <h4>Search by author</h4>
            <div class="form-group" name="Search author">
                <label for="SearchTermAuthor" class="control-label"></label>
                <input name="SearchTermAuthor" class="form-control" />
            </div>
            <br>
            <h4>Search by genre</h4>
            <div class="form-group" name="Search genre">
                <label for="SearchTermGenre" class="control-label"></label>
                <input name="SearchTermGenre" class="form-control" />
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
                <input type="submit" asp-action="Index" value="Back to List" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>

QuoteApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuoteApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QuoteApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quotes" asp-action="Index">Quotes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quotes" asp-action="ShowSearchForm">Quotes Search</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - QuoteApp - Developed by - @Environment.MachineName
        </div>


    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>